import type { Mission } from "./mission"

export const SEED_MISSION: Mission = {
  context: {
    constraints: [
      { id: "constraint-car", label: "car available", status: "active" },
      { id: "constraint-dog", label: "dog with us", status: "active" },
      {
        id: "constraint-drive",
        label: "max 20 min drive",
        status: "active",
      },
      {
        id: "constraint-dinner",
        label: "keep dinner at 18:30",
        status: "active",
      },
    ],
    currentLocation: {
      label: "Bike parking, Baška Voda",
      lat: 43.3569,
      lng: 16.9502,
    },
    currentTime: "2026-08-30T15:10:00+02:00",
    energy: "medium",
  },
  date: "2026-08-30",
  events: [],
  id: "baska-voda-demo",
  revision: 6,
  schemaVersion: 1,
  stops: [
    {
      durationMinutes: 210,
      id: "gravel-loop",
      kind: "activity",
      location: {
        label: "Bike parking, Baška Voda",
        lat: 43.3569,
        lng: 16.9502,
      },
      locked: false,
      rationale: "A shaded gravel loop above the coast to start the adventure.",
      startsAt: "2026-08-30T11:30:00+02:00",
      status: "active",
      title: "Forest gravel loop",
      travelMinutesFromPrevious: 0,
    },
    {
      durationMinutes: 90,
      id: "biokovo-hike",
      kind: "activity",
      location: {
        label: "Biokovo trailhead",
        lat: 43.3407,
        lng: 17.061,
      },
      locked: false,
      rationale: "A steep sunset hike if the group still has energy.",
      startsAt: "2026-08-30T15:30:00+02:00",
      status: "planned",
      title: "Biokovo sunset hike",
      travelMinutesFromPrevious: 35,
    },
    {
      durationMinutes: 45,
      id: "return-shower",
      kind: "transition",
      location: {
        label: "Baška Voda apartment",
        lat: 43.3578,
        lng: 16.9491,
      },
      locked: false,
      rationale: "Reset before the evening reservation.",
      startsAt: "2026-08-30T17:15:00+02:00",
      status: "planned",
      title: "Return & shower",
      travelMinutesFromPrevious: 25,
    },
    {
      durationMinutes: 90,
      id: "dinner",
      kind: "meal",
      location: {
        label: "Baška Voda old town",
        lat: 43.3573,
        lng: 16.9507,
      },
      locked: true,
      note: "Reservation for 18:30",
      rationale: "The one commitment the rest of the day must protect.",
      startsAt: "2026-08-30T18:30:00+02:00",
      status: "planned",
      title: "Dinner reservation",
      travelMinutesFromPrevious: 5,
    },
  ],
  timezone: "Europe/Zagreb",
  title: "Baška Voda Adventure",
}
