export const COPY = {
  addItem: "Add item",
  addItemHint: "Add item and press Enter",
  addRequirement: "Add requirement",
  addRequirementHint: "Add requirement and press Enter",
  activityAriaLabel: "Activity log",
  activityEmpty: "No changes yet. Human and agent decisions will appear here.",
  activityTitle: "History",
  agentHint: "Paste the copied prompt into ChatGPT to build or update this board with Site Tools.",
  boardTitle: "Board title",
  close: "Close",
  closeMenu: "Close menu",
  constraintsTitle: "Operating constraints",
  contextTitle: "Context",
  copyPrompt: "Copy prompt for ChatGPT",
  copiedPrompt: "Prompt copied",
  currentLocation: "Current position",
  currentTime: "Local time",
  demoPrompt:
    "Open https://sidequest-webmcp-eta.vercel.app and use its Site Tools. We are in Baška Voda and our day changed. Read the current Sidequest mission. The gravel ride is complete, we are low on energy, and the Biokovo hike is no longer a good fit. Use reliable sources to find a relaxed swim stop and a fuel stop within our constraints. Keep our 18:30 dinner unchanged. Make the required updates on the Sidequest board, not just in the chat.",
  done: "Mark done",
  editItemTitle: "Edit item title",
  editRequirement: "Edit requirement",
  energy: "Group energy",
  emptyPlanHint:
    "Copy the prompt below into ChatGPT. This page is the plan it reads and updates with Site Tools.",
  freshPrompt:
    "Open https://sidequest-webmcp-eta.vercel.app and use its Site Tools. Read the current Sidequest board. This is a new plan. Ask me for the goal, current location, available time, energy, and any hard constraints that are missing. Research reliable options when needed, then create a practical ordered plan on the Sidequest board. Keep locked items unchanged. Update the board with the available tools, not just in the chat.",
  googleMapsPreview: "Google Maps preview",
  loadDemo: "Load demo",
  loadDemoConfirm: "Replace the current plan with the Baška Voda demo?",
  lock: "Lock",
  mapCaption: "Choose an item, then open it in your preferred maps app.",
  mapTitle: "Route",
  missionViews: "Mission views",
  newPlan: "New plan",
  newPlanConfirm: "Replace the current plan with a blank one?",
  newRequirement: "New requirement",
  noMapItems: "No locations to show.",
  openMenu: "Open menu",
  openInAppleMaps: "Open in Apple Maps",
  openInGoogleMaps: "Open in Google Maps",
  planTitle: "Plan",
  routeItems: "Plan locations",
  scheduleTitle: "Schedule",
  skip: "Skip",
  tagline: "Your day changed. Your plan should too.",
  undo: "Restore",
  unlock: "Unlock",
  unlockToEdit: "Unlock to edit",
  view: "View",
  viewOnMap: "View on map",
  webMcpChecking: "Checking site tools…",
  webMcpConnected: "Site tools connected",
  webMcpError: "Site tools could not connect · manual controls remain available",
  webMcpUnavailable: "Manual mode · open in ChatGPT or enable Chrome WebMCP",
} as const
