export const COPY = {
  activityEmpty: "No changes yet. Human and agent decisions will appear here.",
  activityTitle: "Activity log",
  agentEyebrow: "ChatGPT handoff",
  agentTitle: "Let the agent repair the day",
  appName: "SIDEQUEST",
  constraintsTitle: "Operating constraints",
  contextTitle: "Live context",
  copyPrompt: "Copy replanning prompt",
  copiedPrompt: "Prompt copied",
  currentLocation: "Current position",
  currentTime: "Local time",
  demoPrompt:
    "We are in Baška Voda and our day changed. Read the current Sidequest mission. The gravel ride is complete, we are low on energy, and the Biokovo hike is no longer a good fit. Use reliable sources to find a relaxed swim stop and a fuel stop within our constraints. Keep our 18:30 dinner unchanged. Make the required updates with the available site tools and update the Sidequest board, not just the chat.",
  done: "Done",
  energy: "Group energy",
  mapCaption: "Route overview · not turn-by-turn navigation",
  mapTitle: "Mission route",
  missionEyebrow: "LIVE DAY OPERATIONS",
  reset: "Reset demo",
  resetConfirm: "Reset the mission to its revision 6 demo state?",
  skip: "Skip",
  tagline: "Your day changed. Your plan should too.",
  timelineTitle: "Field plan",
  undo: "Undo",
  webMcpChecking: "Checking site tools…",
  webMcpConnected: "Site tools connected",
  webMcpError: "Site tools could not connect · manual controls remain available",
  webMcpUnavailable: "Manual mode · open in ChatGPT or enable Chrome WebMCP",
} as const
