export const COPY = {
  addItem: "Add item",
  addItemHint: "Add item and press Enter",
  addRequirement: "Add requirement",
  addRequirementHint: "Add requirement and press Enter",
  activityAriaLabel: "Activity log",
  activityEmpty: "No changes yet. Human and agent decisions will appear here.",
  activityTitle: "History",
  agentHint: "Paste the copied prompt into ChatGPT to replan this board with Site Tools.",
  boardTitle: "Board title",
  close: "Close",
  closeMenu: "Close menu",
  constraintsTitle: "Operating constraints",
  contextTitle: "Context",
  copyPrompt: "Copy prompt for ChatGPT",
  copiedPrompt: "Prompt copied",
  currentLocation: "Current position",
  currentTime: "Local time",
  demoPrompt:
    "We are in Baška Voda and our day changed. Read the current Sidequest mission. The gravel ride is complete, we are low on energy, and the Biokovo hike is no longer a good fit. Use reliable sources to find a relaxed swim stop and a fuel stop within our constraints. Keep our 18:30 dinner unchanged. Make the required updates with the available site tools and update the Sidequest board, not just the chat.",
  done: "Mark done",
  editItemTitle: "Edit item title",
  editRequirement: "Edit requirement",
  energy: "Group energy",
  googleMapsPreview: "Google Maps preview",
  lock: "Lock",
  mapCaption: "Choose an item, then open it in your preferred maps app.",
  mapTitle: "Route",
  missionViews: "Mission views",
  newRequirement: "New requirement",
  noMapItems: "No locations to show.",
  openMenu: "Open menu",
  openInAppleMaps: "Open in Apple Maps",
  openInGoogleMaps: "Open in Google Maps",
  planTitle: "Plan",
  reset: "Reset demo",
  resetConfirm: "Reset the mission to its revision 6 demo state?",
  routeItems: "Plan locations",
  scheduleTitle: "Schedule",
  skip: "Skip",
  tagline: "Your day changed. Your plan should too.",
  undo: "Restore",
  unlock: "Unlock",
  unlockToEdit: "Unlock to edit",
  view: "View",
  viewOnMap: "View on map",
  webMcpChecking: "Checking site tools…",
  webMcpConnected: "Site tools connected",
  webMcpError: "Site tools could not connect · manual controls remain available",
  webMcpUnavailable: "Manual mode · open in ChatGPT or enable Chrome WebMCP",
} as const
